### ISSUE TITLE
Enable GraphiQL

### ISSUE THREAD

**Issue by jgcmarins** [Deniscapp/chuck-say-graphql-server#1]
It would be nice to query through GraphiQL.
References: https://github.com/graphql/graphiql

**Comment by deniscapp** [comment]
@jgcmarins GraphiQL is already enabled. I've been doing queries with it.

**Comment by jgcmarins** [comment]
wow, my bad.
I did not saw this: https://github.com/Deniscapp/chuck-say-graphql-server/blob/master/server.js#L10
sorry.
