### ISSUE TITLE
RootQuery with no arguments

### ISSUE THREAD

**Issue by deniscapp** [Deniscapp/chuck-say-graphql-server#2]
I put a new field `categories` on my `RootQuery`, with the idea of writing a simple query like this just for me to get all the available categories:

`categories()`

With no arguments at all. However, it did not work as expected and I am using a `name` argument.
Any tips on this?

**Comment by jgcmarins** [comment]
`categories` can be added just like any other normal field (with or without args).
For example, like this one: https://github.com/Deniscapp/chuck-say-graphql-server/blob/master/schema/schema.js#L25
You can send a PR of a WIP and I can review \o/

**Comment by deniscapp** [comment]
You are right, I was using a wrong syntax for querying 😅

**Comment by jgcmarins** [comment]
Great! \o/
